name: typecheck

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # We stick to Python 3.13 since qiskit-aer is not available yet for Python 3.14.
  # See https://github.com/Qiskit/qiskit-aer/issues/2378.
  python-version: "3.13"

jobs:
  mypy-pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all, necessary to find tags and branches
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,extra,typing]
          pip install --no-deps -e .[no-deps]

      - run: mypy

      - run: pyright